### ISSUE TITLE
where is caffe/proto/caffe.pb.h?

### ISSUE THREAD

**Issue by shomedas** [tenstep/DeepModel#1]
There is no caffe/proto/caffe.pb.h at  https://github.com/BVLC/caffe

which version of caffe do we need to use?

kindly advice

**Comment by xingyizhou** [comment]
Hi shomedas:
  caffe/protp/caffe.pb.h is generated when caffe is compiling, if an error occurs, just make again.

**Comment by shomedas** [comment]
Hi,

```
 I would like to thank you for your prompt reply. i checked my previous
```

version of caffe and figured that it would be generated automatically.

Sorry for the trouble.

With Regards
Shome
CVAI lab,
IISc, Bangalore
