### ISSUE TITLE
An issue about the RGB （480*460*3) picture

### ISSUE THREAD

**Issue by hellojialee** [tenstep/DeepModel#14]
HI~ I come here to ask for your help again.
Why the NYU Hand Dataset's RGB picture quality is so poor? It's not clear. They look so weird.
Could you please give me a hand? The dataset's author seems not to answer issues.
Thank you!

**Comment by xingyizhou** [comment]
Hi, actually I haven't looked into the RGB images of NYU dataset. Maybe the issue comes from the 
inherent flaw of PrimeScene Camera, but I don't know how to fix it.

**Comment by hellojialee** [comment]
Well, thank you all the same!!
