### ISSUE TITLE
details of pose parameter theta

### ISSUE THREAD

**Issue by shomedas** [tenstep/DeepModel#2]
In deepmodel.prototxt which is the layer that outputs "55 dimensional pose parameter theta" . Is it the layer called "DoF"? But it has only 47 num_output.

What is the order of the parameters in the pose parameter theta? Is it the bend, side , twist for each joint of libhand model. What is the joint sequence?

**Comment by strawberryfg** [comment]
Hi, our original hand model has 55 DoF, but our final hand model layer (reported in the paper) outputs 47 values. 
While only 26 are tunable and the remaining 21 DoF are constants used to fix little_finger_mcp, ring_finger_mcp, middle_finger_mcp, index_finger_mcp and thumb_mcp on the palm.
As this is not the final version, our current "HandDefine.h" includes detailed joint sequence, bone sequence, dof sequence and other settings, which will be available soon.

**Comment by shomedas** [comment]
is it 26 or 28 tunable DOFs. Looking at your paper Figure 2 and removing joint as described above i get 
2*3 for each finger, 2+1+1 for thumb: total 28 tunable DOF.

**Comment by strawberryfg** [comment]
2+1+1 for each finger, and 6 DoF for global translation and global rotation, 26 tunable DoF in total. 26 + 3 \* 7 = 47, 21 DoF are fixed constants used to fix the seven joints on the palm. 
Is it convenient for you to give me your e-mail address and I will send you some details.

**Comment by shomedas** [comment]
I sent an email to zhouxy13@fudan.edu.cn from my id. Thanx

**Comment by jiangwei221** [comment]
Thanks for open sourcing your code!
I don't understand the 31 joints hand model, could you publish a picture of the new skeleton model?
Thanks!
--update--
I think that the extra 8 joints belongs to the 4 fingers. One for fingertip, and one for the connection to palm. I'm confused why we need 2 fixed joints to locate each finger (except the fingertip)?

**Comment by strawberryfg** [comment]
Hi @jiangwei221,
   I have uploaded the modified version of our code to https://github.com/strawberryfg/DeepModel_hand. Details on Joint/Bone/DoF definition etc. can be found in the include and source file as well as in "illustration of model.jpg". Note that the current illustration figure is quite ugly, I will upload a clearer visualization of our kinematic model as soon as possible. Please feel free to contact me at strawberryfgalois@gmail.com. 
Thanks for your interest!
