### ISSUE TITLE
NYU Dataset dist convert

### ISSUE THREAD

**Issue by gjtjx** [tenstep/DeepModel#5]
How to convert a NYU Dataset png img pixel value to z dist value?

**Comment by xingyizhou** [comment]
z = b + g \* 256, where b and g are the blue and green channels of the pixel.

**Comment by gjtjx** [comment]
and how to generate png img by z dist？

**Comment by xingyizhou** [comment]
For the images to train and test the network, the z distance is normalized to be zero centered and range -1 ~ 1. For images in the demo folder, I re-scale the testing image to 0~255. It is just for visualization and not the real z value. If you want to recover the z value, you can add the real 3d location of root joint and re-scale by the cube size (300 in our case, you can find detail in training/GetH5DataNYU.py ), then you can write the b and g value as described above. Hope I have correctly understood your question.
