### ISSUE TITLE
How to set init parameters?

### ISSUE THREAD

**Issue by zhangjiasy** [tenstep/DeepModel#6]
How did you set init 47 DOF parameters？ Assigned a sample as default hand pose and calculated it's DOF parameters through the joints' locations?

**Comment by strawberryfg** [comment]
The default canonical pose is set to the first frame of NYU dataset. The initial DoF parameters are therefore recovered by PSO with supervision of 2D ground truth annotations.

**Comment by strawberryfg** [comment]
The default canonical pose is set to the first frame of NYU dataset. The initial DoF parameters are therefore recovered by PSO with supervision of 3D joint ground truth annotations.
