### ISSUE TITLE
No need to change caffe.proto ?

### ISSUE THREAD

**Issue by davidsonic** [tenstep/DeepModel#7]
What's confusing me is that you have added a new loss layer to caffe,  and registered it. Is there no need to change caffe.proto?

**Comment by davidsonic** [comment]
And when running python demo.py in the directory of testing, I got "Check failed, registry.count(type)==1 (0 vs 1) Unknown layer type: DeepHandModel"

**Comment by xingyizhou** [comment]
Hi davidsonic,
  Since our layer does not require specific layer parameters, there is no need to change caffe.proto. For the Unknown layer type Error, it seems you haven't set up the code successfully, please make sure you have followed the instruction and set the pycaffe_root correctly.

**Comment by davidsonic** [comment]
Thanks, I tried either adding the definitions into caffe.proto and without. It turned out that both would work. Any way thank you for your reply.
