### ISSUE TITLE
Rotation Angle Constraints

### ISSUE THREAD

**Issue by karanahujax** [tenstep/DeepModel#9]
In your paper, you have mentioned:

"Each rotation angle has a range [theta_i; theta_i], which are the lower/upper bounds for the
angle. Such bounds avoid self-collision and physically infeasible poses."

Could you please point me to the values of these bounds for each joint and degree of freedom.

**Comment by xingyizhou** [comment]
Hi karanahujax, 
  Thanks for your interests on our work, the constraints are in  https://github.com/tenstep/DeepModel/blob/master/training/configuration/DofConstraintUp.txt and https://github.com/tenstep/DeepModel/blob/master/training/configuration/DofConstraintLow.txt, in radian measure. It is obtained from the training data.
